apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-container
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 581910837730.dkr.ecr.ap-northeast-1.amazonaws.com/sample-container:${{ SHA }}
        ports:
        - containerPort: 80