name: Action Sample

on:
  push:
    branches: 
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ECR_REGISTRY: 581910837730.dkr.ecr.ap-northeast-1.amazonaws.com # ECRレジストリURL
  ECR_REPOSITORY: sample-container # ECRリポジトリ名

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - uses: docker/login-action@v1
        with:
          registry: ${{ env.ECR_REGISTRY }}

      - uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:nginx"
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy:
    needs: build
    # kubectlとaws-cliは"ubuntu-latest"に含まれるので、バージョン指定の必要がなければ、installやsetupもいらない。
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # AWSにCI用のIAMユーザを作りその認証情報をSecretsに設定しておく。そして、AWS公式の認証用Actionの引数に渡す。
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          role-duration-seconds: 1200
      - name: Configure EKS
        run: |
          # eksの認証情報を更新する。このコマンドを呼べばkubeconfigの内容をSecretに設定することは不要。
          aws eks update-kubeconfig --name test
      - name: Deploy to EKS
        run: |
          # サンプルなのでget pod。実際はkubectl applyなりhelm upgradeなりを呼ぶ。
          kubectl get pod